version: '3.4'

services:
  shop:
    image: shop
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports: 
      - "3000:3000"
  
  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  backend:
    container_name: "backend"
    build: ./backend/
    ports: 
      - "8000:8000"
    depends_on: 
      - "database"
      
